PROCEDURE MAIN()
	CREATE_TABLE_ENCAISSE_TABLE()
RETURN

PROCEDURE CREATE_TABLE_ENCAISSE_TABLE()
	CREATE TempEncaisseTable
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "NUM_TABLE", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 3, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK

	REPLACE FIELD_NAME WITH "NB_CLIENT", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 2, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "T_CB", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 7, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "T_CHQ", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 7, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK

	REPLACE FIELD_NAME WITH "T_ESP", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 7, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "T_TRESTO", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 7, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TOTAL", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 8, ;
			FIELD_DEC WITH 2
			
	CLOSE TempEncaisseTable		
	CREATE EncaissementTable FROM TempEncaisseTable
RETURN 