PROCEDURE MAIN()
	CREATE_STOCK_TABLE()
RETURN

PROCEDURE CREATE_STOCK_TABLE
	CREATE TempStockTable
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "DATE", ;
			FIELD_TYPE WITH "D"

	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CODE_PLAT", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 4, ;
			FIELD_DEC WITH 0
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "QUANTITE", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 4, ;
			FIELD_DEC WITH 0
	
	CLOSE TempStockTable
	
	CREATE StockTable FROM TempStockTable
RETURN