PROCEDURE MAIN
	CREATE_BILANM()
RETURN

PROCEDURE CREATE_BILANM()
	CREATE TEMP_BILANM
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "ANNEE", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 4, ;
			FIELD_DEC WITH 0
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "MOIS", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 2, ;
			FIELD_DEC WITH 0
					
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "NB_CLIENT", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 10, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TOTAL", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2	
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "ST_55", ;   // sous total des montants en 5.5
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "ST_196", ;  // sous total des montants en 19.6
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TVA_1", ;       // TVA a 5.5 %
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 10, ;
			FIELD_DEC WITH 2
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TVA_2", ;       // TVA a 19.6 %
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 10, ;
			FIELD_DEC WITH 2	
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "SERVICE", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "EMPORTE", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CB", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2	

	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CHQ", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "ESP", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TR", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
			
	CLOSE TEMP_BILANM
	CREATE BILANM FROM TEMP_BILANM
RETURN