PROCEDURE MAIN
	CREATE_RECETTEJ()
RETURN

PROCEDURE CREATE_RECETTEJ()
	CREATE TEMP_RECETTEJ
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "DATE", ;
			FIELD_TYPE WITH "D"
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "NUM_TABLE", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 3, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK

	REPLACE FIELD_NAME WITH "NFACT", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 7, ;
			FIELD_DEC WITH 0
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "NB_CLIENT", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 10, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TOTAL", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2	
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TVA", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 10, ;
			FIELD_DEC WITH 2
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "SERVICE", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "EMPORTE", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CB", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2	

	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CHQ", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "ESP", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TR", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 12, ;
			FIELD_DEC WITH 2
	
	APPEND BLANK
		
	REPLACE FIELD_NAME WITH "STATUS", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 1, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "TIC_PRINT", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 1, ;
			FIELD_DEC WITH 0
		
	CLOSE TEMP_RECETTEJ
	CREATE RECETTEJ FROM TEMP_RECETTEJ
RETURN