PROCEDURE MAIN()
	CREATE_TABLE_MENU()
RETURN

PROCEDURE CREATE_TABLE_MENU
	CREATE Temp
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CODE_PLAT", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 4, ;
			FIELD_DEC WITH 0
	
	APPEND BLANK

	REPLACE FIELD_NAME WITH "LIBELLE", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 32, ;
			FIELD_DEC WITH 0
			
	APPEND BLANK
			
	REPLACE FIELD_NAME WITH "PRIX", ;
			FIELD_TYPE WITH "N", ;
			FIELD_LEN WITH 10, ;
			FIELD_DEC WITH 2
			
	APPEND BLANK
	
	REPLACE FIELD_NAME WITH "CATEGORIE", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 1, ;
			FIELD_DEC WITH 0
			
	APPEND BLANK		
			
	REPLACE FIELD_NAME WITH "STOCKAGE", ;
			FIELD_TYPE WITH "C", ;
			FIELD_LEN WITH 1, ;
			FIELD_DEC WITH 0
	
	CLOSE Temp
	CREATE Menu FROM Temp
RETURN